# prepare

In [15]:
## ------- edit params first here --------------

# COSMIC_VER = ['v2','v3']
COSMIC_VER = 'v2'
WES_DB = 'wes-db'
RNA_DB = 'rna-db'
WORKER = None

INPUTROOT = 'export_c3/'
OUTPUTROOT = 'external_data/a_new_exteranl_validation_data/washed/'

# ------------------------------------------------

DBLIBPATH = '[GCpytools_path]'
# RPLOTLIB = '[lib_path]/yutils.R'
# RPLOTLIB = '[lib_path]/yplot.R'

# ------------- optional --------------------------
## utils for plotting
# import seaborn as sns
# sns.set(color_codes=True)
# from matplotlib import pyplot as plt
# from glob import glob

# utils for os.path
from os.path import join as J
from os.path import exists as E
from os import listdir as L
print('global L,E,J is defined')

#---------------- setup PATHs -------------------
## setup WORKDIR
import os
# Change WORKDIR working directory depend on your projext location
WORKDIR = os.getcwd()

## setup OUTPUTPATH and WOKER
import sys

# SET OUTPUT DIR
OUTPUTPATH = os.path.join(WORKDIR,OUTPUTROOT)

if DBLIBPATH not in sys.path:
    sys.path.insert(0,DBLIBPATH)

if WORKDIR != '' :
    if  os.path.exists(WORKDIR):
        os.chdir(WORKDIR)
    else:
        raise ValueError(f'WORKDIR path {WORKDIR} do not exist.')


## setup WOKER
# from dalibs import yglobal
# BASE_HTTP = yglobal.conf['META']['BASE_URL']
# if WORKER is not None:
#     WORKER = yglobal.ypull_current_worker()

# def getcwdurl():
#     p = WORKDIR.replace('[JUP_ROOT]/',BASE_HTTP)
#     print(p)
WORKER = None

#---------------- load librarys -------------------

from tqdm.notebook import tqdm

## to reload modules
# import dalibs
# import importlib
# importlib.reload(dalibs)

## set up db
from dblibs import *
db = Database(outputdir = OUTPUTROOT,input_dir = INPUTROOT, set_used_db=WES_DB)
echo.set(8,10, maxrow=150)
del OUTPUTPATH

#---------------------------------------------------
# getcwdurl()
print(f'[info] Current Worker is >> {WORKER} << working @',os.getcwd())
db

global L,E,J is defined
⚠ set default global used db to [wes-db]
[info] Current Worker is >> None << working @ [PROJECT_ROOT]/ALLNEW_PLOTS/DATA_AVA

Log_system(outputdir="external_data/a_new_exteranl_validation_data/washed/",input_dir="export_c3/", use_full_path=True)
  cur_db_key = wes-db
  OUTPUTDIR = external_data/a_new_exteranl_validation_data/washed/
  INPUTDIR = export_c3/
  Verbose = True

## whole NEW Data

### wash data

In [4]:
d1 = db.importing('external_data/a_new_exteranl_validation_data/external_data/public_data_summary/public_data_summary_dataset_info.xlsx')
d1['dir'] = 'external_data/a_new_exteranl_validation_data/external_data/public_data_summary/'
d2 = db.importing('external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/collaborator_dataset_info.xlsx')
d2['dir'] = 'external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/'

[05/05 06:03:43]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/public_data_summary_dataset_info.xlsx
  Sheets list: ['Sheet1']
  Read the 1 / 1 sheet named <Sheet1>
[05/05 06:03:43]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/collaborator_dataset_info.xlsx
  Sheets list: ['Sheet1']
  Read the 1 / 1 sheet named <Sheet1>

In [5]:
ref = pd.concat([d1,d2],ignore_index=True)
ref = ref[ref['是否带预后'] == '是']
ref = ref[ref['备注'] != 'same as collaborator data'].drop_index()
ref['文件名'] = ref['文件名'].str.replace('/','_',regex=False)
ref = ref.rename(columns = {'文件名':'folder'})
ref['name'] = ['2016_TCGA','2018_Cancer_cell','2023_Mol_Cell','2019_PNAS', '2024_CRM', '2024_natcan']
ref

,folder,数据类型,例数,前列腺癌阶段,是否带预后,PMID,备注,dir,name
0,2016 TCGA-RNAseqIndex of _runs_stddata__2016_0...,RNA-seq,498,PCa,是,-,NaN,external_data/a_new_exteranl_validation_data/e...,2016_TCGA
1,2018 Cancer cell-RNAseq-292例初诊未治,RNA-seq,118,PCa,是,30537516,NaN,external_data/a_new_exteranl_validation_data/e...,2018_Cancer_cell
2,2023 Mol Cell Proteomics-蛋白质组-78例mHSPC,Proteomics,78,mCSPC,是,37394064,研究终点为进展到CRPC,external_data/a_new_exteranl_validation_data/e...,2023_Mol_Cell
3,2019-PNAS_Genomic_clinical_outcome,RNA-seq,266例CRPC,CRPC,是,31061129,NaN,external_data/a_new_exteranl_validation_data/e...,2019_PNAS
4,2024-CRM,proteomics,306,PCa-低中高危,是,39168102,NaN,external_data/a_new_exteranl_validation_data/e...,2024_CRM
5,2024-natcan,RNA-seq (TPM)+proteomics,Protein: 125 (tumors + NATs)\nRNA-seq: 247 tumors,PCa-高危,是,39242942,NaN,external_data/a_new_exteranl_validation_data/e...,2024_natcan

In [6]:
db.exporting(ref, 'file_list.txt',outputdir='external_data/a_new_exteranl_validation_data/')

[05/05 06:03:57] writing 1 file with 6 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/file_list.txt

In [7]:
for _, row in ref.iterrows():
    p = J(row['dir'],row['folder'])
    break
    if not E(p):
        print(p)

In [8]:
ref = db.importing('file_list.txt', frm = 'external_data/a_new_exteranl_validation_data/')
ref

[05/05 06:04:16]reading external_data/a_new_exteranl_validation_data/file_list.txt

,folder,数据类型,例数,前列腺癌阶段,是否带预后,PMID,备注,dir,name
0,2016 TCGA-RNAseqIndex of _runs_stddata__2016_0...,RNA-seq,498,PCa,是,-,NaN,external_data/a_new_exteranl_validation_data/e...,2016_TCGA
1,2018 Cancer cell-RNAseq-292例初诊未治,RNA-seq,118,PCa,是,30537516,NaN,external_data/a_new_exteranl_validation_data/e...,2018_Cancer_cell
2,2023 Mol Cell Proteomics-蛋白质组-78例mHSPC,Proteomics,78,mCSPC,是,37394064,研究终点为进展到CRPC,external_data/a_new_exteranl_validation_data/e...,2023_Mol_Cell
3,2019-PNAS_Genomic_clinical_outcome,RNA-seq,266例CRPC,CRPC,是,31061129,NaN,external_data/a_new_exteranl_validation_data/e...,2019_PNAS
4,2024-CRM,proteomics,306,PCa-低中高危,是,39168102,NaN,external_data/a_new_exteranl_validation_data/e...,2024_CRM
5,2024-natcan,RNA-seq (TPM)+proteomics,Protein: 125 (tumors + NATs)\nRNA-seq: 247 tumors,PCa-高危,是,39242942,NaN,external_data/a_new_exteranl_validation_data/e...,2024_natcan

####  2016_TCGA

In [9]:
row = ref.iloc[0]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'], 'prad_tcga', )
fdir,L(fdir)

2016_TCGA

('external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2016 TCGA-RNAseqIndex of _runs_stddata__2016_01_28_data_PRAD_20160128/prad_tcga',
 ['.DS_Store',
  'case_lists',
  'data_clinical_patient.txt',
  'data_clinical_sample.txt',
  'data_cna.txt',
  'data_cna_hg19.seg',
  'data_gistic_genes_amp.txt',
  'data_gistic_genes_del.txt',
  'data_linear_cna.txt',
  'data_methylation_hm450.txt',
  'data_mrna_seq_v2_rsem.txt',
  'data_mrna_seq_v2_rsem_zscores_ref_all_samples.txt',
  'data_mrna_seq_v2_rsem_zscores_ref_diploid_samples.txt',
  'data_mutations.txt',
  'data_mutsig.txt',
  'data_rppa.txt',
  'data_rppa_zscores.txt',
  'LICENSE',
  'meta_clinical_patient.txt',
  'meta_clinical_sample.txt',
  'meta_cna.txt',
  'meta_cna_hg19_seg.txt',
  'meta_gistic_genes_amp.txt',
  'meta_gistic_genes_del.txt',
  'meta_linear_cna.txt',
  'meta_methylation_hm450.txt',
  'meta_mrna_seq_v2_rsem.txt',
  'meta_mrna_seq_v2_rsem_zscores_ref_all_samples.txt',
  'meta_mrna_seq_v2_rsem_zscores_ref_diploid_samples.txt',
  'meta_mutations.txt',
  'meta_mutsig.txt',
  'meta_rppa.txt',
  'meta_rppa_zscores.txt',
  'meta_study.txt'])

In [10]:
cp = db.importing(J(fdir,'data_clinical_patient.txt'), comment='#')
cs = db.importing(J(fdir,'data_clinical_sample.txt'), comment='#')

[05/05 06:04:34]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2016 TCGA-RNAseqIndex of _runs_stddata__2016_01_28_data_PRAD_20160128/prad_tcga/data_clinical_patient.txt
[05/05 06:04:34]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2016 TCGA-RNAseqIndex of _runs_stddata__2016_01_28_data_PRAD_20160128/prad_tcga/data_clinical_sample.txt

In [11]:
clin1 = cp[['PATIENT_ID','OS_STATUS','OS_MONTHS', 'DFS_STATUS', 'DFS_MONTHS']]
clin2 = cs[['PATIENT_ID','SAMPLE_ID']]
clin = pd.merge(clin2,clin1, how='right', on='PATIENT_ID')
clin['OS_STATUS'] = clin['OS_STATUS'].str[0].astype(int)
clin['OS_MONTHS'] = clin['OS_MONTHS'].astype(float)
clin.loc[clin['DFS_STATUS']=='[Not Available]'] = "2"
clin['DFS_STATUS'] = clin['DFS_STATUS'].str[0].astype(int)
clin.loc[clin['DFS_STATUS'] == 2,'DFS_STATUS'] = np.nan
clin['DFS_MONTHS'] = clin['DFS_MONTHS'].astype(float)
clin

       PATIENT_ID        SAMPLE_ID OS_STATUS OS_MONTHS  DFS_STATUS  DFS_MONTHS
0    TCGA-2A-A8VL  TCGA-2A-A8VL-01         0      20.4         0.0       20.40
1    TCGA-2A-A8VO  TCGA-2A-A8VO-01         0     55.88         0.0       55.88
2    TCGA-2A-A8VT  TCGA-2A-A8VT-01         0     45.11         0.0       45.11
3    TCGA-2A-A8VV  TCGA-2A-A8VV-01         0     22.04         0.0       22.04
..            ...              ...       ...       ...         ...         ...
497  TCGA-ZG-A9MC  TCGA-ZG-A9MC-01         0     14.95         0.0       14.95
498  TCGA-ZG-A9N3  TCGA-ZG-A9N3-01         0     11.47         0.0       11.47
499  TCGA-ZG-A9ND  TCGA-ZG-A9ND-01         0     13.47         0.0       13.47
500  TCGA-ZG-A9NI  TCGA-ZG-A9NI-01         0      4.34         0.0        4.34

[501 rows x 6 columns]

In [12]:
df = db.importing(J(fdir, 'data_mrna_seq_v2_rsem.txt'))


df = df.set_index('Hugo_Symbol')
df = df.loc[:,df.columns!='Entrez_Gene_Id']
df[df==0] = np.nan
df = df[~df.index.duplicated()]
df

[05/05 06:04:38]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2016 TCGA-RNAseqIndex of _runs_stddata__2016_01_28_data_PRAD_20160128/prad_tcga/data_mrna_seq_v2_rsem.txt

,TCGA-2A-A8VL-01,TCGA-2A-A8VO-01,TCGA-2A-A8VT-01,TCGA-2A-A8VV-01,TCGA-2A-A8VX-01,...,TCGA-ZG-A9M4-01,TCGA-ZG-A9MC-01,TCGA-ZG-A9N3-01,TCGA-ZG-A9ND-01,TCGA-ZG-A9NI-01
Hugo_Symbol,,,,,,,,,,,
LOC100130426,NaN,NaN,NaN,NaN,NaN,...,0.4443,NaN,NaN,NaN,NaN
UBE2Q2P3,20.7518,19.3206,48.8860,21.7343,2.9525,...,19.4917,13.1381,6.4103,10.4997,13.9401
HMGB1P1,80.9114,62.0757,94.4228,108.1492,96.9240,...,124.4212,105.5155,126.9525,64.4925,79.0267
TIMM23,1311.0196,864.0084,582.7206,918.6963,832.8505,...,451.5164,510.5105,1520.3891,1186.9272,1313.6042
...,...,...,...,...,...,...,...,...,...,...,...
FLJ10821,1488.6715,854.0391,2081.2500,1029.7682,837.3851,...,1211.8753,1448.4484,773.5493,1340.4807,598.1859
ZZZ3,505.1493,640.6955,1373.5294,1049.0646,752.7396,...,550.6194,607.1071,740.6761,605.2222,518.5280
TPTEP1,199.2791,291.7690,36.0294,21.1790,13.6037,...,32.4648,56.5566,12.3275,687.5324,45.0894
AKR1C6P,NaN,NaN,0.3676,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN

In [13]:
x = list(set(df.columns) & set(clin['SAMPLE_ID']))
df = df.loc[:,x]
clin = clin.set_index('SAMPLE_ID').loc[x]
clin.index.name = "id"
clin

                   PATIENT_ID OS_STATUS OS_MONTHS  DFS_STATUS  DFS_MONTHS
id
TCGA-EJ-5494-01  TCGA-EJ-5494         0     48.52         0.0       48.52
TCGA-G9-6498-01  TCGA-G9-6498         0     64.13         1.0       44.09
TCGA-G9-6366-01  TCGA-G9-6366         0     63.96         0.0       63.96
TCGA-VP-A87E-01  TCGA-VP-A87E         0     66.92         0.0       66.92
...                       ...       ...       ...         ...         ...
TCGA-HC-A48F-01  TCGA-HC-A48F         0     22.34         0.0       22.34
TCGA-V1-A9OA-01  TCGA-V1-A9OA         0     20.89         0.0       20.89
TCGA-XJ-A9DX-01  TCGA-XJ-A9DX         0     31.96         0.0       31.96
TCGA-KC-A7F6-01  TCGA-KC-A7F6         0      8.64         0.0        8.64

[492 rows x 5 columns]

In [16]:
OUTPUTROOT

'external_data/a_new_exteranl_validation_data/washed/'

In [17]:
db.exporting(clin, f"{name}__clin",outputdir=OUTPUTROOT)

db.exporting(df,f"{name}__rna_count",outputdir=OUTPUTROOT)

[05/05 06:05:12] writing 1 file with 492 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2016_TCGA__clin.dfx
[05/05 06:05:19] writing 1 file with 20514 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2016_TCGA__rna_count.dfx

#### 2018_Cancer_cell

In [18]:
row = ref.iloc[1]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'],'prostate_dkfz_2018')
fdir,L(fdir)

2018_Cancer_cell

('external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2018 Cancer cell-RNAseq-292例初诊未治/prostate_dkfz_2018',
 ['.DS_Store',
  'case_lists',
  'data_clinical_patient.txt',
  'data_clinical_sample.txt',
  'data_mrna_seq_rpkm.txt',
  'data_mrna_seq_rpkm_zscores_ref_all_samples.txt',
  'data_mutations.txt',
  'meta_clinical_patient.txt',
  'meta_clinical_sample.txt',
  'meta_mrna_seq_rpkm.txt',
  'meta_mrna_seq_rpkm_zscores_ref_all_samples.txt',
  'meta_mutations.txt',
  'meta_study.txt',
  'sv_data.txt'])

In [19]:
cp = db.importing(J(fdir, 'data_clinical_patient.txt'),comment='#')
cs = db.importing(J(fdir, 'data_clinical_sample.txt'),comment='#')
clin1 = cp[['PATIENT_ID','BCR_STATUS','TIME_FROM_SURGERY_TO_BCR_LASTFU']]
clin1.columns = ['PATIENT_ID','BCR_STATUS','BCR_MONTH']
clin2 = cs[['PATIENT_ID','SAMPLE_ID']]
clin = pd.merge(clin2,clin1, how='right', on='PATIENT_ID')
clin

[05/05 06:05:27]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2018 Cancer cell-RNAseq-292例初诊未治/prostate_dkfz_2018/data_clinical_patient.txt
[05/05 06:05:27]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2018 Cancer cell-RNAseq-292例初诊未治/prostate_dkfz_2018/data_clinical_sample.txt

      PATIENT_ID        SAMPLE_ID  BCR_STATUS  BCR_MONTH
0       CPCG0001         CPCG0001         1.0      114.9
1       CPCG0004         CPCG0004         1.0       53.1
2       CPCG0015         CPCG0015         1.0       51.2
3       CPCG0019         CPCG0019         1.0       90.9
..           ...              ...         ...        ...
320  ICGC_PCAL45  ICGC_PCAL45_T01         1.0        1.8
321  ICGC_PCAL46  ICGC_PCAL46_T01         0.0       21.2
322  ICGC_PCAL47  ICGC_PCAL47_T01         1.0        1.6
323  ICGC_PCAL48  ICGC_PCAL48_T01         1.0        3.0

[324 rows x 4 columns]

In [20]:
df = db.importing(J(fdir, 'data_mrna_seq_rpkm.txt'))
df = df.loc[:, df.columns != 'Entrez_Gene_Id'].set_index('Hugo_Symbol')
x = list(set(df.columns) & set(clin['SAMPLE_ID']))
df = df.loc[:,x]
print(len(x))
clin = clin.set_index('SAMPLE_ID').loc[x]
clin.index.name = "id"
df

[05/05 06:05:29]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2018 Cancer cell-RNAseq-292例初诊未治/prostate_dkfz_2018/data_mrna_seq_rpkm.txt
118

,ICGC_PCA106_T01,ICGC_PCA187_T01,ICGC_PCA027_T02,ICGC_PCA007_T01,ICGC_PCA059_T01,...,ICGC_PCA034_T05,ICGC_PCA091_T01,ICGC_PCA001_T01,ICGC_PCA038_T05,ICGC_PCA069_T01
Hugo_Symbol,,,,,,,,,,,
TSPAN6,8.423168,38.823790,31.647667,5.096353,25.408411,...,17.783870,10.596195,5.554278,17.241351,24.269818
TNMD,0.110421,0.376956,0.021297,0.048112,0.249327,...,0.250538,0.326775,0.020083,0.731432,0.050441
DPM1,6.848927,30.782953,26.639981,4.416495,38.731413,...,24.285841,10.945427,6.982991,11.619069,22.236734
SCYL3,2.231469,4.587687,5.979826,5.325382,4.891131,...,3.258472,2.547200,3.660459,2.297618,4.235823
...,...,...,...,...,...,...,...,...,...,...,...
AC104389.2,0.000000,0.000000,0.000000,0.011996,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000
NHLRC4,1.002902,2.140168,3.343376,0.893199,0.479319,...,1.190078,0.958073,0.540185,1.347724,0.983773
AL773572.1,0.000000,0.000000,0.014150,0.000000,0.003582,...,0.082354,0.154391,0.065829,0.000000,0.000000
AC016590.1,0.028948,0.017737,0.039083,0.070327,0.018843,...,0.080660,0.025383,0.079560,0.116213,0.035262

In [21]:
name

'2018_Cancer_cell'

In [22]:
db.exporting(clin, f"{name}__clin",outputdir=OUTPUTROOT)

db.exporting(df,f"{name}__rna_rpkm",outputdir=OUTPUTROOT)

[05/05 06:05:32] writing 1 file with 118 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2018_Cancer_cell__clin.dfx
[05/05 06:05:34] writing 1 file with 20881 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2018_Cancer_cell__rna_rpkm.dfx

#### 2023_Mol_Cell

In [23]:
row = ref.iloc[2]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'])
fdir,L(fdir)

2023_Mol_Cell

('external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2023 Mol Cell Proteomics-蛋白质组-78例mHSPC',
 ['cli（进展到CRPC的时间）.csv', 'HSPC蛋白组学文章.pdf', 'mhspc-seq.csv'])

In [24]:
data = db.importing(J(fdir, 'mhspc-seq.csv'),sep=',').set_index('Gene')
data.columns = "X" + data.columns
data

[05/05 06:05:43]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2023 Mol Cell Proteomics-蛋白质组-78例mHSPC/mhspc-seq.csv

,X2_1,X2_10,X2_11,X2_13,X2_14,...,X4_5,X4_6,X4_7,X4_8,X4_9
Gene,,,,,,,,,,,
YWHAB,19.873097,18.443444,19.463369,19.591080,19.045027,...,13.566222,17.662946,18.050459,16.984047,18.762645
YWHAE,17.657700,16.498801,17.695549,17.700567,17.112522,...,NaN,16.056470,16.601709,15.038062,16.314941
YWHAH,13.993920,14.983918,15.833549,14.931409,15.018140,...,NaN,14.349404,14.858935,14.363248,13.641380
YWHAG,17.410919,15.711409,17.264280,17.421664,16.920247,...,NaN,17.313804,17.349913,16.398751,17.564910
...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,5.393298,NaN,-1.688730,9.461839,3.242508,...,NaN,NaN,NaN,NaN,NaN
ZYX,16.561681,13.898112,15.693763,16.582268,16.991292,...,NaN,17.180659,17.255834,17.405207,15.919956
ZZEF1,11.388044,10.657685,11.516815,11.758703,11.240461,...,NaN,NaN,10.215624,6.581367,10.984248
ZZZ3,8.939399,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN

In [25]:
clin0 = db.importing(J(fdir, 'cli（进展到CRPC的时间）.csv'),sep=',')
clin0.columns = ['Patient_ID','OS_STATUS','OS_MONTH']
x = list(set(clin0['Patient_ID']) & set(data.columns))
print(len(x))

clin = clin0.set_index('Patient_ID').loc[x]
clin.index.name = "id"
df = data.loc[:,x]
df

[05/05 06:05:43]reading external_data/a_new_exteranl_validation_data/external_data/public_data_summary/2023 Mol Cell Proteomics-蛋白质组-78例mHSPC/cli（进展到CRPC的时间）.csv
78

,X2_11,X3_37,X4_11,X3_18,X3_2,...,X3_31,X3_14,X3_12,X3_5,X4_8
Gene,,,,,,,,,,,
YWHAB,19.463369,18.191586,17.618955,19.272623,16.550373,...,18.886280,18.609447,18.312910,17.283295,16.984047
YWHAE,17.695549,16.590391,16.332257,17.398591,16.003061,...,17.804950,17.473864,16.017730,17.192033,15.038062
YWHAH,15.833549,14.136951,13.542788,14.687141,14.836602,...,15.347474,15.078607,14.546682,14.849106,14.363248
YWHAG,17.264280,17.360896,16.886494,18.734234,16.041095,...,17.220188,18.813523,16.777250,16.535491,16.398751
...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,-1.688730,NaN,-1.774486,NaN,NaN,...,9.123612,NaN,NaN,NaN,NaN
ZYX,15.693763,16.243200,16.840880,16.025074,17.066539,...,15.751626,15.554576,16.273060,17.049095,17.405207
ZZEF1,11.516815,11.401906,12.317129,12.254078,10.353405,...,12.913489,11.361179,10.577179,9.597818,6.581367
ZZZ3,NaN,NaN,NaN,NaN,NaN,...,11.509617,11.471181,NaN,NaN,NaN

In [26]:

db.exporting(clin, f"{name}__clin",outputdir=OUTPUTROOT)

db.exporting(df,f"{name}__rna_tpm",outputdir=OUTPUTROOT)

[05/05 06:05:44] writing 1 file with 78 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2023_Mol_Cell__clin.dfx
[05/05 06:05:45] writing 1 file with 7295 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2023_Mol_Cell__rna_tpm.dfx

#### 2019_PNAS

In [27]:
row = ref.iloc[3]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'])
fdir,L(fdir)

2019_PNAS

('external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2019-PNAS_Genomic_clinical_outcome',
 ['expression_266_samples.txt', 'prad_su2c_2019_clinical_data.tsv'])

In [28]:
data = db.importing(J(fdir,'expression_266_samples.txt')).set_index('Hugo_Symbol')
data

[05/05 06:05:47]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2019-PNAS_Genomic_clinical_outcome/expression_266_samples.txt

,TP_2077_Tumor,TP_2078_Tumor,SC_9056_T,SC_9137_Tumor,SC_9139_Tumor,...,WCM89_X1,WCM393_Z3,WCM573_X1,WCM665_X1,WCM666_X1
Hugo_Symbol,,,,,,,,,,,
A1BG,1.191379,0.496139,0.782425,2.655721,3.436719,...,1.209215,1.341221,12.942821,12.977479,3.508555
A1CF,0.018454,0.019613,0.527011,0.014175,0.022547,...,0.198950,0.031614,0.020294,3.393404,0.519557
A2M,76.101400,53.507200,18.366020,55.398322,190.431669,...,47.413525,4.995954,16.707539,20.410717,107.862080
A2ML1,0.111239,7.958060,0.071234,0.070876,0.380227,...,0.085616,0.387282,0.026637,0.746213,0.046233
...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,6.327768,6.161690,4.268103,5.387722,5.896602,...,4.424099,5.695745,3.806707,5.534475,2.231400
ZYX,37.632641,26.907844,25.414817,25.348517,89.576291,...,14.425222,34.797090,26.528957,10.051621,45.340561
ZZEF1,14.173005,10.990751,5.224719,3.606209,6.313283,...,6.806590,15.865402,7.402148,13.521897,6.090573
ZZZ3,12.617786,10.284213,9.761127,10.534085,7.823901,...,11.936801,12.938207,4.634153,15.472986,9.343405

In [29]:
clin0 = db.importing(J(fdir,'prad_su2c_2019_clinical_data.tsv'))
# clin0
clin0 = clin0[['Patient ID','Sample ID','Overall Survival (Months)', 'Overall Survival Status']]
clin0.columns = ['Patient ID','Sample ID','OS_MONTHS','OS_STATUS']
clin0 = clin0[~clin0['OS_STATUS'].isna()]
clin0['OS_STATUS'] = clin0['OS_STATUS'].str[0].astype(int)
x = list(set(clin0['Sample ID']) & set(data.columns))
len(x)


clin = clin0.set_index('Sample ID').loc[x]
clin.index.name = "id"
df = data.loc[:,x]
df

[05/05 06:05:47]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2019-PNAS_Genomic_clinical_outcome/prad_su2c_2019_clinical_data.tsv

,SC_9183_T,SC_9175_T,TP_2078_Tumor,WCM335_X1,SC_9035_T,...,SC_9124_Tumor,SC_9086_T,SC_9181_T,SC_9137_Tumor,MO_1510_T
Hugo_Symbol,,,,,,,,,,,
A1BG,1.148766,26.483760,0.496139,0.979354,1.529517,...,0.266784,1.925443,9.195867,2.655721,6.719077
A1CF,0.018210,0.009578,0.019613,0.073233,0.024647,...,1.483581,0.035209,0.049279,0.014175,0.069315
A2M,96.634777,38.356145,53.507200,8.739815,33.849796,...,29.167398,161.084660,11.535927,55.398322,33.632810
A2ML1,0.089232,0.005587,7.958060,5.425513,1.451145,...,0.130392,0.699542,2.946554,0.070876,0.100390
...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,5.558362,8.672852,6.161690,8.554889,5.942601,...,8.678288,2.701093,6.851304,5.387722,9.276573
ZYX,57.273350,14.496103,26.907844,18.175647,22.589312,...,13.060929,38.749367,8.679691,25.348517,21.177166
ZZEF1,10.407513,5.999214,10.990751,9.177838,9.922663,...,7.821595,3.824499,2.325037,3.606209,6.793460
ZZZ3,12.857655,5.364489,10.284213,11.161405,16.312264,...,17.251068,5.450880,12.770568,10.534085,12.515169

In [30]:
db.exporting(clin, f"{name}__clin",outputdir=OUTPUTROOT)

db.exporting(df,f"{name}__rna_tpm",outputdir=OUTPUTROOT)

[05/05 06:05:48] writing 1 file with 19 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_PNAS__clin.dfx
[05/05 06:05:49] writing 1 file with 19293 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_PNAS__rna_tpm.dfx

#### 2024_CRM

In [31]:
row = ref.iloc[4]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'])
fdir,L(fdir)

2024_CRM

('external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-CRM',
 ['surgical_306_normal_10055_proteins.txt',
  'surgical_306_patients_survival.txt',
  'surgical_306_tumor_average_10055_proteins.txt'])

In [32]:
clin0 = db.importing(J(fdir,'surgical_306_patients_survival.txt'))
print(clin0.columns)
clin0 = clin0[['Patient_ID','BCR','BCR_time']]
clin0.columns = ['Patient_ID','BCR_STATUS','BCR_MONTH']
clin0 = clin0[~clin0['BCR_STATUS'].isna()]
print(clin0['BCR_STATUS'].unique())
clin0['Sample_ID'] = clin0['Patient_ID']+'_1'
clin0

[05/05 06:05:51]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-CRM/surgical_306_patients_survival.txt
Index(['Patient_ID', 'Age', 'Gleason', 'Pathological_stage', 'pre_PSA',
       'D_Amico', 'BCR_PSA', 'BCR', 'BCR_time'],
      dtype='object')
[1. 0.]

    Patient_ID  BCR_STATUS  BCR_MONTH    Sample_ID
0      PCSHA_1         1.0       94.0    PCSHA_1_1
1      PCSHA_3         1.0     1258.0    PCSHA_3_1
2      PCSHA_5         1.0       43.0    PCSHA_5_1
3      PCSHA_6         1.0       45.0    PCSHA_6_1
..         ...         ...        ...          ...
302  PCSHA_354         1.0       29.0  PCSHA_354_1
303  PCSHA_355         0.0       25.0  PCSHA_355_1
304  PCSHA_356         0.0     1185.0  PCSHA_356_1
305  PCSHA_357         1.0     1039.0  PCSHA_357_1

[305 rows x 4 columns]

In [33]:
data = db.importing(J(fdir,'surgical_306_tumor_average_10055_proteins.txt'))
data.index.name = 'SYMBOL'
data

[05/05 06:05:52]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-CRM/surgical_306_tumor_average_10055_proteins.txt

,PCSHA_1_1,PCSHA_3_1,PCSHA_5_1,PCSHA_6_1,PCSHA_7_1,...,PCSHA_321_1,PCSHA_322_1,PCSHA_323_1,PCSHA_324_1,PCSHA_325_1
SYMBOL,,,,,,,,,,,
NUDT4B,3722.535,5265.050,1807.515,3307.5300,4033.5400,...,0.0,0.0,0.0,0.0,0.0
IGKV3-7,133595.200,286350.550,215587.500,200972.0000,179221.1000,...,0.0,0.0,0.0,0.0,0.0
IGLV4-69,39319.700,21469.125,17077.100,15277.5750,28161.2000,...,0.0,0.0,0.0,0.0,0.0
IGLV8-61,14705.100,8777.560,23430.650,14169.6000,22999.6300,...,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
ZHX2,10628.100,6867.060,10014.085,7125.0650,6130.0550,...,0.0,0.0,0.0,0.0,0.0
MORC2,2513.030,3834.030,5369.060,2592.0200,1603.0145,...,0.0,0.0,0.0,0.0,0.0
IVNS1ABP,2510.030,0.000,2218.015,1076.0155,1485.5100,...,0.0,0.0,0.0,0.0,0.0
SEC23IP,68409.550,57002.450,40910.350,23708.1500,133326.9000,...,0.0,0.0,0.0,0.0,0.0

In [34]:
x = list(set(data.columns) & set(clin0['Sample_ID']))
print(len(x))

clin = clin0.set_index('Sample_ID').loc[x]
clin.index.name = "id"
df = data.loc[:,x]
df

305

,PCSHA_138_1,PCSHA_178_1,PCSHA_74_1,PCSHA_66_1,PCSHA_143_1,...,PCSHA_282_1,PCSHA_15_1,PCSHA_300_1,PCSHA_357_1,PCSHA_242_1
SYMBOL,,,,,,,,,,,
NUDT4B,0.00,0.000,0.0000,0.00,0.000,...,0.000,10791.610,0.000,0.000,0.0
IGKV3-7,177975.05,61713.400,98218.6500,23404.15,79973.010,...,184122.000,294225.000,318615.500,8613.625,545301.5
IGLV4-69,0.00,11830.570,9262.0600,0.00,23064.600,...,14346.600,42877.200,40535.225,12556.570,0.0
IGLV8-61,0.00,18642.650,37726.2500,0.00,9712.075,...,21085.650,36903.750,35154.700,18624.600,0.0
...,...,...,...,...,...,...,...,...,...,...,...
ZHX2,0.00,4624.545,4759.0500,0.00,2292.020,...,3945.545,2357.525,4863.555,4562.550,0.0
MORC2,0.00,3436.535,950.0115,0.00,1407.520,...,0.000,7930.560,0.000,0.000,0.0
IVNS1ABP,0.00,0.000,0.0000,0.00,0.000,...,0.000,2102.025,0.000,0.000,0.0
SEC23IP,30954.75,26505.200,57147.9500,22761.68,16836.150,...,36728.350,21160.665,36425.350,32235.750,30650.3

In [35]:
db.exporting(clin, f"{name}__clin",outputdir=OUTPUTROOT)

db.exporting(df,f"{name}__prt",outputdir=OUTPUTROOT)

[05/05 06:05:54] writing 1 file with 305 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_CRM__clin.dfx
[05/05 06:05:55] writing 1 file with 10055 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_CRM__prt.dfx

#### 2024_natcan

In [36]:
row = ref.iloc[5]
name = row['name']
print(name)
fdir = J(row['dir'],row['folder'])
fdir,L(fdir)

2024_natcan

('external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-natcan',
 ['clinical_information.txt',
  'natCan_247_samples_TPM.txt',
  'natCan_protein_expression_zscore.txt',
  'sample_information.txt'])

In [37]:
clin0 = db.importing(J(fdir,'clinical_information.txt'))
print(clin0.columns)
clin0 = clin0[['HRR_ID','SampleID','BCR_event','BCR_time']]
clin0.columns = ['HRR_ID','SampleID','BCR_STATUS','BCR_MONTH']
clin0 = clin0[~clin0['BCR_STATUS'].isna()]
print(clin0['BCR_STATUS'].unique())
clin0['BCR_STATUS'] = [1 if i=='Yes' else 0 if i=='No' else np.nan for i in clin0['BCR_STATUS']]
clin0

[05/05 06:05:56]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-natcan/clinical_information.txt
Index(['HRR_ID', 'SampleID', 'PSA', 'Pathology_T_stage', 'BCR_event',
       'BCR_time', 'Tumor_purity'],
      dtype='object')
['No' 'Yes']

        HRR_ID SampleID  BCR_STATUS  BCR_MONTH
0    HRR893281    PC62T           0     1451.0
1    HRR893287    PC66T           1       59.0
2    HRR893295    PC71T           0     1815.0
3    HRR893187   PC149T           1      103.0
..         ...      ...         ...        ...
121  HRR893279    PC61T           0     1882.0
122  HRR893277    PC60T           1       92.0
123  HRR893087    PC02T           1      342.0
124  HRR893183   PC147T           0      299.0

[113 rows x 4 columns]

In [38]:
data = db.importing(J(fdir,'natCan_247_samples_TPM.txt'))
data = data.set_index('genename')
data

[05/05 06:05:57]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-natcan/natCan_247_samples_TPM.txt

,HRR893084,HRR893085,HRR893086,HRR893087,HRR893088,...,HRR893326,HRR893327,HRR893328,HRR893329,HRR893330
genename,,,,,,,,,,,
WASH7P,2.605,2.964,0.983,0.409,1.072,...,0.103,1.376,1.212,1.154,1.134
AL627309.6,1.452,4.608,1.175,4.254,2.987,...,2.930,1.081,0.543,1.200,0.313
AL627309.7,5.488,20.601,2.342,9.749,15.596,...,6.796,0.318,0.000,2.657,0.969
AL627309.5,0.298,0.488,0.219,0.184,0.682,...,0.168,0.084,0.088,0.587,0.187
...,...,...,...,...,...,...,...,...,...,...,...
AC233755.2,1.178,1.075,7.916,0.376,1.095,...,4.645,7.096,3.832,0.685,0.534
AC233755.1,0.000,0.301,7.895,1.578,1.377,...,2.952,8.010,3.211,0.574,4.700
AC240274.1,12.911,9.690,5.603,9.236,10.476,...,7.884,8.469,7.422,9.228,24.507
U1,0.703,2.892,7.435,1.350,15.223,...,4.593,21.015,11.241,3.068,2.873

In [39]:
x = list(set(data.columns) & set(clin0['HRR_ID']))
print(len(x))
df = data.loc[:,x]
clin = clin0.set_index("HRR_ID").loc[x]
clin.index.name = "id"
df

113

,HRR893219,HRR893201,HRR893129,HRR893099,HRR893135,...,HRR893269,HRR893095,HRR893326,HRR893197,HRR893191
genename,,,,,,,,,,,
WASH7P,2.698,2.310,0.429,3.781,0.782,...,2.058,0.836,0.103,3.018,6.199
AL627309.6,10.581,2.757,0.401,0.501,0.247,...,1.256,0.718,2.930,5.681,3.379
AL627309.7,29.008,6.062,0.000,0.887,0.000,...,5.004,0.795,6.796,14.501,20.166
AL627309.5,0.487,0.165,0.063,0.201,0.012,...,0.234,0.108,0.168,0.611,0.724
...,...,...,...,...,...,...,...,...,...,...,...
AC233755.2,0.339,0.816,0.343,3.433,0.000,...,0.000,1.228,4.645,0.000,5.565
AC233755.1,0.000,4.335,0.431,5.748,0.177,...,0.000,0.000,2.952,1.211,2.469
AC240274.1,14.812,28.459,3.203,3.377,11.958,...,104.820,6.562,7.884,20.356,41.982
U1,26.791,15.623,3.999,4.229,1.703,...,15.160,6.331,4.593,6.214,16.726

In [40]:
data2 = db.importing(J(fdir,'natCan_protein_expression_zscore.txt'))
data2 = data2.set_index('Protein')
data2

[05/05 06:06:00]reading external_data/a_new_exteranl_validation_data/external_data/public_data_collaborator/data_for_collaborator/2024-natcan/natCan_protein_expression_zscore.txt

,PC01T,PC02T,PC03T,PC04T,PC05T,...,PC95N,PC96N,PC97N,PC98N,PC99N
Protein,,,,,,,,,,,
A1BG,-0.331920,0.569224,-0.049434,-0.019590,-0.807562,...,0.335275,0.840027,-0.159384,-0.047547,0.550832
A1CF,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
A2M,-0.686667,0.260931,0.160629,-0.054623,-0.644935,...,0.261215,0.558728,0.252128,1.143828,0.320823
A2ML1,NaN,NaN,0.341957,NaN,NaN,...,NaN,0.663248,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
ZW10,-0.157501,-0.234169,-0.109005,0.000039,0.619899,...,0.025484,-0.198243,-0.443746,-0.003528,0.473182
ZYG11B,-0.036110,NaN,-0.019778,NaN,NaN,...,NaN,0.000208,NaN,NaN,-0.301728
ZYX,-0.176018,-0.272371,0.408839,0.053615,-0.717956,...,0.837093,-0.178757,0.650052,0.164425,0.306612
ZZEF1,0.045992,0.107382,0.113874,0.136750,-0.033662,...,-0.647918,0.277171,0.099024,0.030970,-0.011251

In [41]:
x2 = list(set(data2.columns) & set(clin0['SampleID']))
print(len(x2))
df2 = data2.loc[:,x2]
clin2 = clin0.set_index("SampleID").loc[x2]
clin2.index.name = "id"
df2

113

,PC142T,PC02T,PC111T,PC125T,PC122T,...,PC105T,PC15T,PC93T,PC13T,PC81T
Protein,,,,,,,,,,,
A1BG,0.151108,0.569224,-0.750325,0.197681,-0.062940,...,0.264073,0.344824,-0.629518,-0.247553,-0.575028
A1CF,NaN,NaN,-0.307223,0.184610,NaN,...,NaN,NaN,1.111028,NaN,NaN
A2M,0.231258,0.260931,-0.802838,0.442904,0.307150,...,0.663604,-0.025527,-0.117748,-0.224708,-1.216904
A2ML1,NaN,NaN,-0.898454,NaN,0.933823,...,NaN,0.588063,-0.332982,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
ZW10,0.110775,-0.234169,-0.060975,-0.000068,-0.066878,...,0.159868,-0.155770,-0.253230,0.143590,-0.004547
ZYG11B,NaN,NaN,0.019790,NaN,NaN,...,NaN,0.172831,-0.536819,NaN,NaN
ZYX,0.586866,-0.272371,0.078224,0.387216,-0.033865,...,0.095874,-0.124224,0.186299,-0.315567,-0.392232
ZZEF1,0.041540,0.107382,-0.046438,0.276659,0.194014,...,0.179625,-0.183177,0.105171,-0.028659,0.328184

In [42]:
db.exporting(clin, f"{name}__rna_clin",outputdir=OUTPUTROOT)
db.exporting(clin2, f"{name}__prt_clin",outputdir=OUTPUTROOT)

[05/05 06:06:02] writing 1 file with 113 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_natcan__rna_clin.dfx
[05/05 06:06:02] writing 1 file with 113 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_natcan__prt_clin.dfx

In [43]:
db.exporting(df,f"{name}__rna_tpm",outputdir=OUTPUTROOT)
db.exporting(df2,f"{name}__prt",outputdir=OUTPUTROOT)

[05/05 06:06:05] writing 1 file with 26949 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_natcan__rna_tpm.dfx
[05/05 06:06:06] writing 1 file with 9045 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2024_natcan__prt.dfx

#### 2019_Cancer_Cell

In [44]:
name = '2019_CancerCell'

In [47]:
clin0 = db.importing('external_data/article_data_others_works/PC_CancerCell_Canada/bcr_table_pca_cluster.dfx')
clin0 = clin0[['pid','bcr_months','bcr_status']].copy()
clin0.columns = ['id','BCR_MONTH','BCR_STATUS']
clin0

[05/05 06:07:33]reading external_data/article_data_others_works/PC_CancerCell_Canada/bcr_table_pca_cluster.dfx

          id  BCR_MONTH  BCR_STATUS
0   CPCG0100   0.336756           1
1   CPCG0102   4.128679           1
2   CPCG0103   3.756331           1
3   CPCG0182   6.072553           0
..       ...        ...         ...
69  CPCG0551   4.695414           1
70  CPCG0557   3.375770           1
71  CPCG0584   8.845996           0
72  CPCG0615   7.663244           0

[73 rows x 3 columns]

In [48]:
data = db.importing('external_data/article_data_others_works/PC_CancerCell_Canada/PRAD_CA_x_rna_norm.dfx',index_col=0)
df = data.T
df.index.name = 'normd'
x = list(set(clin0['id']) & set(df.columns))
df = df.loc[:,x]
clin = clin0.set_index("id").loc[x]
display(clin)
df

[05/05 06:07:50]reading external_data/article_data_others_works/PC_CancerCell_Canada/PRAD_CA_x_rna_norm.dfx

          BCR_MONTH  BCR_STATUS
id
CPCG0342   6.663929           0
CPCG0398   6.034223           0
CPCG0339   5.869952           0
CPCG0248   2.795346           1
...             ...         ...
CPCG0241   0.569473           1
CPCG0396   5.629021           0
CPCG0249   2.507871           1
CPCG0457   4.950034           1

[54 rows x 2 columns]

,CPCG0342,CPCG0398,CPCG0339,CPCG0248,CPCG0348,...,CPCG0255,CPCG0241,CPCG0396,CPCG0249,CPCG0457
normd,,,,,,,,,,,
TAPBP,32.014957,15.949195,18.723115,40.016524,17.653661,...,28.779876,41.149044,17.902283,28.785753,27.018191
SMPD1,22.243952,15.364285,15.011473,19.884612,16.374057,...,17.401222,18.482757,21.963277,11.533338,14.875642
PCID2,101.934670,104.501864,108.722638,88.223744,95.939063,...,48.564356,95.852251,98.365337,100.749169,150.855914
KTI12,0.612724,0.585748,0.481336,0.526126,0.495625,...,0.333825,0.342070,0.437942,0.505826,0.479773
...,...,...,...,...,...,...,...,...,...,...,...
PTPN13,50.361940,33.679148,65.967935,58.003511,60.354338,...,97.715376,73.603479,119.830993,66.635326,66.868934
IVD,29.185806,30.728264,29.496510,41.014519,50.015781,...,52.218863,38.435153,70.320410,48.121335,37.380712
SERPINH1,38.362058,37.294346,28.646094,27.964542,29.830653,...,23.761132,40.223949,31.875047,35.462820,20.176215
SCFD1,266.996432,281.266553,273.274653,272.396564,225.310870,...,221.190128,299.109171,285.775246,205.044380,280.241736

In [49]:
df2 = db.importing('external_data/article_data_others_works/PC_CancerCell_Canada/prt_mat_ssgsea_input.dfx')
df2.index.name = 'prt'
x = list(set(clin0['id']) & set(df2.columns))
df2 = df2.loc[:,x]
clin2 = clin0.set_index('id').loc[x]
display(clin2)
df2

[05/05 06:08:27]reading external_data/article_data_others_works/PC_CancerCell_Canada/prt_mat_ssgsea_input.dfx

          BCR_MONTH  BCR_STATUS
id
CPCG0342   6.663929           0
CPCG0557   3.375770           1
CPCG0242   0.265572           1
CPCG0398   6.034223           0
...             ...         ...
CPCG0396   5.629021           0
CPCG0182   6.072553           0
CPCG0249   2.507871           1
CPCG0457   4.950034           1

[73 rows x 2 columns]

,CPCG0342,CPCG0557,CPCG0242,CPCG0398,CPCG0248,...,CPCG0241,CPCG0396,CPCG0182,CPCG0249,CPCG0457
prt,,,,,,,,,,,
A2M,-0.212561,0.278212,-0.687265,-0.653316,-0.201600,...,-0.380831,-0.715289,-0.502192,-0.418296,-0.796208
AAAS,-0.325560,0.662478,0.739957,-0.562109,-0.520510,...,1.029771,-0.717269,-0.523186,1.327042,-0.620169
ABAT,0.175398,-0.508035,-0.324464,-0.572058,-0.164897,...,-0.155531,-0.526330,-0.532723,-0.013960,-0.554005
ABCA8,-0.470671,-0.566812,-0.465603,-0.612074,0.521501,...,-0.534654,-0.650664,-0.442142,-0.094998,-0.648272
...,...,...,...,...,...,...,...,...,...,...,...
YWHAQ,-0.160569,-0.425268,-0.743119,-0.566765,0.273455,...,-0.677099,-0.653297,0.065399,-0.748479,-0.657937
YWHAZ,0.084853,-0.222534,-0.735529,-0.555518,0.374357,...,-0.752237,-0.642747,-0.020443,-0.743010,-0.582052
ZW10,-0.366731,-0.555107,-0.148239,-0.525815,-0.152687,...,-0.262217,-0.533438,-0.340785,-0.108682,-0.613710
ZYX,-0.013314,0.447004,-0.763837,-0.511992,0.273782,...,-0.772662,-0.713732,-0.039590,-0.699757,-0.692808

In [50]:
name

'2019_CancerCell'

In [51]:
db.exporting(clin,f"{name}__rna_clin",outputdir=OUTPUTROOT)
db.exporting(clin2,f"{name}__prt_clin",outputdir=OUTPUTROOT)
db.exporting(df,f"{name}__rna_normd",outputdir=OUTPUTROOT)
db.exporting(df2,f"{name}__prt",outputdir=OUTPUTROOT)

[05/05 06:08:31] writing 1 file with 54 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_CancerCell__rna_clin.dfx
[05/05 06:08:31] writing 1 file with 73 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_CancerCell__prt_clin.dfx
[05/05 06:08:31] writing 1 file with 7299 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_CancerCell__rna_normd.dfx
[05/05 06:08:31] writing 1 file with 1756 lines at
	[PROJECT_ROOT]/external_data/a_new_exteranl_validation_data/washed/2019_CancerCell__prt.dfx

### gen GSEA

In [52]:
base = 'external_data/a_new_exteranl_validation_data/washed/'
# gseas = [i for i in L(base) if 'ssgsea' in i]
# gseas

In [53]:
name

'2019_CancerCell'

In [54]:
m1 = {
    '2016_TCGA':'2016_TCGA_rna_count_ssgsea.dfx',
    '2018_Cancer_cell':'2018_Cancer_cell_rna_rpkm_ssgsea.dfx',
    '2019_PNAS':'2019_PNAS_rna_tpm_ssgsea.dfx',
    '2023_Mol_Cell':'2023_Mol_Cell_rna_tpm_ssgsea.dfx',
    '2024_CRM':'2024_CRM_prt_ssgsea.dfx',
    '2024_natcan_prt':'2024_natcan_prt_ssgsea.dfx',
    '2024_natcan_rna':'2024_natcan_rna_tpm_ssgsea.dfx',
    '2019_CancerCell_prt':"2019_CancerCell__prt.dfx",
    '2019_CancerCell_rna':"2019_CancerCell__rna_normd.dfx",
}
m2 = {
    '2016_TCGA':'2016_TCGA__clin.dfx',
    '2018_Cancer_cell':'2018_Cancer_cell__clin.dfx',
    '2019_PNAS':'2019_PNAS__clin.dfx',
    '2023_Mol_Cell':'2023_Mol_Cell__clin.dfx',
    '2024_CRM':'2024_CRM__clin.dfx',
    '2024_natcan_prt':'2024_natcan__prt_clin.dfx',
    '2024_natcan_rna':'2024_natcan__rna_clin.dfx',
    '2019_CancerCell_prt':"2019_CancerCell__prt_clin.dfx",
    '2019_CancerCell_rna':"2019_CancerCell__rna_clin.dfx",
}

In [55]:
import joblib
OBJ = joblib.load(filename='export_c3/fig4_gsea_rf_model_evenly_dis')
print(OBJ.keys())
dtc = OBJ['dtc']
matv_ss = OBJ['matv_ss']

dict_keys(['dtc', 'xtest', 'ytest', 'matt_ss', 'matv_ss'])

In [383]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
def standarize(mat):
    """
    mat: index are ssGSEA terms, columns are patients
    Returns:
        StandardScaler scaled dataframe, index are Patients, columns are ssGSEA terms
    """
    mt = mat.T
    x = StandardScaler().fit_transform(mt)
    res = pd.DataFrame(x, index = mt.index, columns=mt.columns)
    return res
import joblib
CACHE = J('export_c3/ext_data_valid_pca_surv_data.joblib')
if E(CACHE):
    print(f'=====\n Load existing cache {CACHE}')
    res = joblib.load(CACHE)
else:
    res = {}
    for name in m1.keys():
        file = m1[name]
        mat = db.importing(J(base, file))
        fclin = m2[name]
        clin = db.importing(J(base, fclin))
        mask = clin.columns.str.endswith('MONTHS')
        s = pd.Series(clin.columns)
        s[mask] = s[mask].str.replace('MONTHS','MONTH', regex=False)
        clin.columns = s
        mask = s.str.endswith('_MONTH')
        os_types = s[mask].str.removesuffix('_MONTH').to_list()
        mask_cols = (s=='id')|(s.str.endswith('_MONTH')|(s.str.endswith('_STATUS')))


        pca = PCA(n_components=4)
        X_r = pd.DataFrame(pca.fit_transform(mat.T),index=mat.columns ,columns=['X1','X2','X3','X4'])

        mat_ss = standarize(mat)
        cls = dtc.predict(mat_ss.loc[:,dtc.feature_names_in_])

        df = pd.DataFrame({"id":mat.columns,"Cluster":cls})

        data_pca = pd.merge( X_r[['X1','X2']]
                            , df,
                    left_index=True,right_on='id',how='left')
        data_pca = pd.merge(data_pca,clin.loc[:,mask_cols.values],on='id',how='left')

        res[name] = {"data_pca":data_pca,'os_types':os_types}

        print(file, data_pca.groupby('Cluster')['id'].count())
    print(f'=====\n Dump cache to {CACHE}')
    joblib.dump(res, CACHE)

[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2016_TCGA_rna_count_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2016_TCGA__clin.dfx
2016_TCGA_rna_count_ssgsea.dfx Cluster
C1     96
C2    130
C3    266
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2018_Cancer_cell_rna_rpkm_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2018_Cancer_cell__clin.dfx
2018_Cancer_cell_rna_rpkm_ssgsea.dfx Cluster
C1    22
C2    21
C3    75
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2019_PNAS_rna_tpm_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2019_PNAS__clin.dfx
2019_PNAS_rna_tpm_ssgsea.dfx Cluster
C1     3
C2     6
C3    10
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2023_Mol_Cell_rna_tpm_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2023_Mol_Cell__clin.dfx
2023_Mol_Cell_rna_tpm_ssgsea.dfx Cluster
C1    23
C2    16
C3    39
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_CRM_prt_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_CRM__clin.dfx
2024_CRM_prt_ssgsea.dfx Cluster
C1     54
C2     47
C3    204
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_natcan_prt_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_natcan__prt_clin.dfx
2024_natcan_prt_ssgsea.dfx Cluster
C1    35
C2    28
C3    50
Name: id, dtype: int64
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_natcan_rna_tpm_ssgsea.dfx
[05/17 08:41:42]reading external_data/a_new_外部数据验证/washed/2024_natcan__rna_clin.dfx
2024_natcan_rna_tpm_ssgsea.dfx Cluster
C1    22
C2    30
C3    61
Name: id, dtype: int64
=====
 Dump cache to export_c3/ext_data_valid_pca_surv_data.joblib

## save data

In [57]:
import joblib
CACHE = J('export_c3/ext_data_valid_pca_surv_data.joblib')
if E(CACHE):
    print(f'=====\n Load existing cache {CACHE}')
    res = joblib.load(CACHE)

=====
 Load existing cache export_c3/ext_data_valid_pca_surv_data.joblib

In [60]:
for tag, values in res.items():
    db.exporting(values['data_pca'],f'ext_data_{tag}_data_pca',outputdir='export_c3/')
    
db.exporting(pd.Series(res.keys()),f'ext_data_glx_source',outputdir='export_c3/')

[05/05 06:12:56] writing 1 file with 492 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2016_TCGA_data_pca.dfx
[05/05 06:12:56] writing 1 file with 118 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2018_Cancer_cell_data_pca.dfx
[05/05 06:12:56] writing 1 file with 19 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2019_PNAS_data_pca.dfx
[05/05 06:12:56] writing 1 file with 78 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2023_Mol_Cell_data_pca.dfx
[05/05 06:12:56] writing 1 file with 305 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2024_CRM_data_pca.dfx
[05/05 06:12:56] writing 1 file with 113 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2024_natcan_prt_data_pca.dfx
[05/05 06:12:56] writing 1 file with 113 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2024_natcan_rna_data_pca.dfx
[05/05 06:12:56] writing 1 file with 73 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2019_CancerCell_prt_data_pca.dfx
[05/05 06:12:56] writing 1 file with 54 lines at
	[PROJECT_ROOT]/export_c3/ext_data_2019_CancerCell_rna_data_pca.dfx
[05/05 06:12:56] writing 1 file with 9 lines at
	[PROJECT_ROOT]/export_c3/ext_data_glx_source.dfx

## PLOT survival

 * Please use notebook 
`Fig1_S1S2_xR_PLOT.ipynb`
**fig S3F S3G S3H** part to generate the survival plot